<?php
/**
 * NotificationsCountResponse
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.0.42
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the NotificationsCountResponse model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class NotificationsCountResponse 
{
        /**
     * @var int|null
     * @SerializedName("all")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $all;

    /**
     * @var int|null
     * @SerializedName("likes")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $likes;

    /**
     * @var int|null
     * @SerializedName("followers")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $followers;

    /**
     * @var int|null
     * @SerializedName("comments")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $comments;

    /**
     * @var int|null
     * @SerializedName("remixes")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $remixes;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->all = isset($data['all']) ? $data['all'] : null;
        $this->likes = isset($data['likes']) ? $data['likes'] : null;
        $this->followers = isset($data['followers']) ? $data['followers'] : null;
        $this->comments = isset($data['comments']) ? $data['comments'] : null;
        $this->remixes = isset($data['remixes']) ? $data['remixes'] : null;
    }

    /**
     * Gets all.
     *
     * @return int|null
     */
    public function getAll(): ?int
    {
        return $this->all;
    }

    /**
     * Sets all.
     *
     * @param int|null $all
     *
     * @return $this
     */
    public function setAll(int $all = null)
    {
        $this->all = $all;

        return $this;
    }

    /**
     * Gets likes.
     *
     * @return int|null
     */
    public function getLikes(): ?int
    {
        return $this->likes;
    }

    /**
     * Sets likes.
     *
     * @param int|null $likes
     *
     * @return $this
     */
    public function setLikes(int $likes = null)
    {
        $this->likes = $likes;

        return $this;
    }

    /**
     * Gets followers.
     *
     * @return int|null
     */
    public function getFollowers(): ?int
    {
        return $this->followers;
    }

    /**
     * Sets followers.
     *
     * @param int|null $followers
     *
     * @return $this
     */
    public function setFollowers(int $followers = null)
    {
        $this->followers = $followers;

        return $this;
    }

    /**
     * Gets comments.
     *
     * @return int|null
     */
    public function getComments(): ?int
    {
        return $this->comments;
    }

    /**
     * Sets comments.
     *
     * @param int|null $comments
     *
     * @return $this
     */
    public function setComments(int $comments = null)
    {
        $this->comments = $comments;

        return $this;
    }

    /**
     * Gets remixes.
     *
     * @return int|null
     */
    public function getRemixes(): ?int
    {
        return $this->remixes;
    }

    /**
     * Sets remixes.
     *
     * @param int|null $remixes
     *
     * @return $this
     */
    public function setRemixes(int $remixes = null)
    {
        $this->remixes = $remixes;

        return $this;
    }
}


